name: Build

on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build ui
        run: |
          npm i
          npm run build
        env:
          CI: true
      - name: run tests
        run: |
          npm i
          npm run test
        env:
          CI: true